# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-14 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('key', models.CharField(max_length=50, verbose_name='类别')),
            ],
            options={
                'verbose_name': '电影类别',
                'verbose_name_plural': '电影类别',
                'db_table': 'tb_film_category',
            },
        ),
    ]
