# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-14 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='片名')),
                ('url', models.CharField(max_length=300, verbose_name='影视链接')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('release_date', models.DateField(max_length=20, verbose_name='上映时间')),
                ('grade', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('director', models.CharField(blank=True, max_length=30, verbose_name='导演')),
                ('protagonist', models.CharField(blank=True, max_length=50, verbose_name='主演')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.FilmCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'tb_film',
            },
        ),
    ]
