# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-14 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='charge',
            field=models.SmallIntegerField(choices=[(0, '免费'), (1, '会员'), (2, '付费')], default=0, verbose_name='费用'),
        ),
        migrations.AddField(
            model_name='film',
            name='fcomment',
            field=models.CharField(max_length=200, null=True, verbose_name='描述信息'),
        ),
    ]
